services:
  - type: web
    name: laravel-github
    env: docker
    repo: https://github.com/Thitipan-James/laravel_github
    branch: main
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /data/database.sqlite
    disk:
      name: data
      mountPath: /data
